version: "3.9"
services:
    postgres:
        container_name: tododb
        image: postgres:latest
        environment:
            POSTGRES_DB: "tododb"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "admin"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres-data: